name: Pull Request Checks

env:
  USE_LOCKFILE: false

on:
  pull_request:
    branches: [ master, alpha, beta ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 14.x]

    steps:

    # region Setup
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get Yarn Cache Path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-node-${{ matrix.node }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-node-${{ matrix.node }}-yarn-
    - run: "echo Yarn Cache Hit: ${{ steps.yarn-cache.outputs.cache-hit != 'true'}}"

    - name: Setting Up Node.js (${{ matrix.node-version }})
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # endregion

    # region Steps
    - run: yarn install --frozen-lockfile
      if: "env.USE_LOCKFILE == 'true'"

    - run: yarn install
      if: "env.USE_LOCKFILE == 'false'"

    - name: Commits to Lint
      run: git log ${{github.event.pull_request.base.sha}}..${{github.event.pull_request.head.sha}} --graph --abbrev-commit --decorate --format=format:'%h%d%n%s (%cr) - %an (%ae)%n%b'

    - name: Lint Commits
      run: yarn commitlint --from ${{github.event.pull_request.base.sha}} --to ${{github.event.pull_request.head.sha}}

    - name: Build
      run: yarn build
    # endregion
